name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted  # Specify self-hosted to use a custom runner like runner1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print current working directory
      run: pwd
