name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: runner1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: print cwd
      run:pwd
     
